---
- name: test cisco version
  hosts: switches,asr
  gather_facts: no
  tasks:
     - name: get cisco version
       ios_command:
           commands: "show run | i domain|name-server"
       register: version
     - copy:
         content: "{{ version.stdout }}"
         dest: "{{ playbook_dir }}/../output/{{ inventory_hostname }}"
       delegate_to: localhost
